package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
)

func main() {
	if len(os.Args) != 3 {
		fatalf("usage: embedskill SOURCE DESTINATION")
	}
	contents, err := os.ReadFile(os.Args[1])
	if err != nil {
		fatalf("read source: %v", err)
	}
	generated := []byte("// Code generated by embedskill; DO NOT EDIT.\n\npackage skill\n\nvar Content = []byte(" + strconv.Quote(string(contents)) + ")\n")
	generated, err = format.Source(generated)
	if err != nil {
		fatalf("format generated source: %v", err)
	}
	if err := atomicWrite(os.Args[2], generated); err != nil {
		fatalf("write destination: %v", err)
	}
}

func atomicWrite(destination string, contents []byte) (returnedErr error) {
	directory := filepath.Dir(destination)
	file, err := os.CreateTemp(directory, "."+filepath.Base(destination)+".tmp-*")
	if err != nil {
		return err
	}
	temporary := file.Name()
	defer func() {
		if returnedErr != nil {
			file.Close()
		}
		os.Remove(temporary)
	}()
	if err := file.Chmod(0o644); err != nil {
		return err
	}
	if _, err := file.Write(contents); err != nil {
		return err
	}
	if err := file.Sync(); err != nil {
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	return atomicReplace(temporary, destination)
}

func fatalf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
