package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/fr3akX/artisan-cli/internal/securefile"
)

var validSkillName = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*$`)

type sourceSpec struct {
	Name string
	Path string
}

func main() {
	if err := runGenerator(os.Args[1:]); err != nil {
		fatalf("%v", err)
	}
}

func runGenerator(args []string) error {
	if len(args) != 2 {
		return errors.New("usage: embedskill SOURCE_ROOT content_generated.go")
	}
	if filepath.IsAbs(args[1]) || filepath.Clean(args[1]) != "content_generated.go" {
		return errors.New("destination must be the local content_generated.go")
	}
	sources := []sourceSpec{
		{Name: "artisan-inventory", Path: filepath.Join(args[0], "artisan-inventory", "SKILL.md")},
		{Name: "artisan-roast-review", Path: filepath.Join(args[0], "artisan-roast-review", "SKILL.md")},
	}
	generated, err := generateRegistry(sources)
	if err != nil {
		return err
	}
	if err := atomicWrite(args[1], generated); err != nil {
		return fmt.Errorf("write destination: %w", err)
	}
	return nil
}

func generateRegistry(sources []sourceSpec) ([]byte, error) {
	ordered := append([]sourceSpec(nil), sources...)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].Name < ordered[j].Name })
	seen := make(map[string]struct{}, len(ordered))
	contents := make(map[string][]byte, len(ordered))
	for _, source := range ordered {
		if !validSkillName.MatchString(source.Name) {
			return nil, fmt.Errorf("invalid skill name %q", source.Name)
		}
		if _, duplicate := seen[source.Name]; duplicate {
			return nil, fmt.Errorf("duplicate skill name %q", source.Name)
		}
		seen[source.Name] = struct{}{}
		value, err := os.ReadFile(source.Path)
		if err != nil {
			return nil, fmt.Errorf("read %s source: %w", source.Name, err)
		}
		frontmatterName, err := parseFrontmatterName(value)
		if err != nil {
			return nil, fmt.Errorf("validate %s source: %w", source.Name, err)
		}
		if frontmatterName != source.Name {
			return nil, fmt.Errorf("source name %q does not match registry name %q", frontmatterName, source.Name)
		}
		contents[source.Name] = value
	}

	var generated bytes.Buffer
	generated.WriteString("// Code generated by embedskill; DO NOT EDIT.\n\npackage skill\n\nconst (\n")
	for _, source := range ordered {
		generated.WriteString("\tgeneratedContent")
		for _, component := range strings.Split(source.Name, "-") {
			generated.WriteString(strings.ToUpper(component[:1]))
			generated.WriteString(component[1:])
		}
		generated.WriteString(" = ")
		generated.WriteString(strconv.Quote(string(contents[source.Name])))
		generated.WriteString("\n")
	}
	generated.WriteString(")\n")
	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func parseFrontmatterName(contents []byte) (string, error) {
	text := string(contents)
	if !strings.HasPrefix(text, "---\n") {
		return "", errors.New("missing frontmatter")
	}
	end := strings.Index(text[4:], "\n---\n")
	if end < 0 {
		return "", errors.New("unterminated frontmatter")
	}
	frontmatter := strings.Split(text[4:4+end], "\n")
	name := ""
	foundName := false
	for _, line := range frontmatter {
		if !strings.HasPrefix(line, "name:") {
			continue
		}
		if foundName {
			return "", errors.New("duplicate frontmatter name")
		}
		foundName = true
		name = strings.TrimSpace(strings.TrimPrefix(line, "name:"))
	}
	if name == "" {
		return "", errors.New("missing frontmatter name")
	}
	return name, nil
}

func atomicWrite(destination string, contents []byte) error {
	return atomicWriteWithOperations(destination, contents,
		func(file *os.File) error { return file.Sync() },
		atomicReplace,
		securefile.SyncParentDirectory,
	)
}

func atomicWriteWithOperations(
	destination string,
	contents []byte,
	syncFile func(*os.File) error,
	replace func(string, string) error,
	syncParent func(string) error,
) (returnedErr error) {
	directory := filepath.Dir(destination)
	file, err := os.CreateTemp(directory, "."+filepath.Base(destination)+".tmp-*")
	if err != nil {
		return err
	}
	temporary := file.Name()
	defer func() {
		_ = file.Close()
		_ = os.Remove(temporary)
	}()
	if err := file.Chmod(0o644); err != nil {
		return err
	}
	if _, err := file.Write(contents); err != nil {
		return err
	}
	if err := syncFile(file); err != nil {
		return fmt.Errorf("sync generated skill: %w", err)
	}
	if err := file.Close(); err != nil {
		return err
	}
	if err := replace(temporary, destination); err != nil {
		return err
	}
	if err := syncParent(directory); err != nil {
		return &securefile.ReplacementError{Err: fmt.Errorf("sync generated skill directory: %w", err)}
	}
	return nil
}

func fatalf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
