package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/fr3akX/artisan-cli/internal/securefile"
)

var validSkillName = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*$`)

type sourceSpec struct {
	Name string
	Path string
}

func main() {
	if err := runGenerator(os.Args[1:]); err != nil {
		fatalf("%v", err)
	}
}

func runGenerator(args []string) error {
	if len(args) != 2 {
		return errors.New("usage: embedskill SOURCE_ROOT content_generated.go")
	}
	if filepath.IsAbs(args[1]) || filepath.Clean(args[1]) != "content_generated.go" {
		return errors.New("destination must be the local content_generated.go")
	}
	sources := []sourceSpec{
		{Name: "artisan-inventory", Path: filepath.Join(args[0], "artisan-inventory", "SKILL.md")},
		{Name: "artisan-roast-review", Path: filepath.Join(args[0], "artisan-roast-review", "SKILL.md")},
	}
	generated, err := generateRegistry(sources)
	if err != nil {
		return err
	}
	if err := atomicWrite(args[1], generated); err != nil {
		return fmt.Errorf("write destination: %w", err)
	}
	return nil
}

func generateRegistry(sources []sourceSpec) ([]byte, error) {
	ordered := append([]sourceSpec(nil), sources...)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].Name < ordered[j].Name })
	seen := make(map[string]struct{}, len(ordered))
	contents := make(map[string][]byte, len(ordered))
	for _, source := range ordered {
		if !validSkillNameValue(source.Name) {
			return nil, fmt.Errorf("invalid skill name %q", source.Name)
		}
		if _, duplicate := seen[source.Name]; duplicate {
			return nil, fmt.Errorf("duplicate skill name %q", source.Name)
		}
		seen[source.Name] = struct{}{}
		value, err := os.ReadFile(source.Path)
		if err != nil {
			return nil, fmt.Errorf("read %s source: %w", source.Name, err)
		}
		frontmatterName, err := parseFrontmatterName(value)
		if err != nil {
			return nil, fmt.Errorf("validate %s source: %w", source.Name, err)
		}
		if frontmatterName != source.Name {
			return nil, fmt.Errorf("source name %q does not match registry name %q", frontmatterName, source.Name)
		}
		contents[source.Name] = value
	}

	var generated bytes.Buffer
	generated.WriteString("// Code generated by embedskill; DO NOT EDIT.\n\npackage skill\n\nconst (\n")
	for _, source := range ordered {
		generated.WriteString("\tgeneratedContent")
		for _, component := range strings.Split(source.Name, "-") {
			generated.WriteString(strings.ToUpper(component[:1]))
			generated.WriteString(component[1:])
		}
		generated.WriteString(" = ")
		generated.WriteString(strconv.Quote(string(contents[source.Name])))
		generated.WriteString("\n")
	}
	generated.WriteString(")\n")
	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func parseFrontmatterName(contents []byte) (string, error) {
	if !utf8.Valid(contents) {
		return "", errors.New("frontmatter must be valid UTF-8")
	}
	text := string(contents)
	if !strings.HasPrefix(text, "---\n") {
		return "", errors.New("missing exact frontmatter opening delimiter")
	}
	lines := strings.Split(text, "\n")
	closing := -1
	for index := 1; index < len(lines); index++ {
		if lines[index] == "---" {
			closing = index
			break
		}
	}
	if closing < 0 {
		return "", errors.New("missing exact frontmatter closing delimiter")
	}
	if closing != 3 {
		return "", errors.New("frontmatter must contain exactly name and description scalars")
	}
	for _, line := range lines[closing+1:] {
		if line == "" {
			continue
		}
		if line == "---" || line == "..." {
			return "", errors.New("extra YAML document is not allowed")
		}
		break
	}

	values := make(map[string]string, 2)
	for _, line := range lines[1:closing] {
		if strings.ContainsAny(line, "\t#") {
			return "", errors.New("frontmatter tabs and comments are not allowed")
		}
		key, value, ok := strings.Cut(line, ": ")
		if !ok || key == "" || value == "" || strings.Contains(key, ":") || strings.TrimSpace(value) != value {
			return "", errors.New("frontmatter entries must be nonempty unquoted scalars")
		}
		if key != "name" && key != "description" {
			return "", fmt.Errorf("unknown frontmatter key %q", key)
		}
		if _, duplicate := values[key]; duplicate {
			return "", fmt.Errorf("duplicate frontmatter key %q", key)
		}
		values[key] = value
	}
	name, hasName := values["name"]
	description, hasDescription := values["description"]
	if !hasName || !hasDescription {
		return "", errors.New("frontmatter requires name and description")
	}
	if containsUnicodeLineOrParagraphSeparator(name) || containsUnicodeLineOrParagraphSeparator(description) {
		return "", errors.New("frontmatter scalars contain a Unicode line or paragraph separator")
	}
	if !validSkillNameValue(name) {
		return "", fmt.Errorf("invalid frontmatter name %q", name)
	}
	if !strings.HasPrefix(description, "Use when ") || strings.Contains(description, ": ") || utf8.RuneCountInString(description) > 1024 {
		return "", errors.New("frontmatter description must be a bounded Use when trigger")
	}
	for _, character := range description {
		if unicode.IsControl(character) {
			return "", errors.New("frontmatter description contains a control character")
		}
	}
	return name, nil
}

func containsUnicodeLineOrParagraphSeparator(value string) bool {
	for _, character := range value {
		if unicode.Is(unicode.Zl, character) || unicode.Is(unicode.Zp, character) {
			return true
		}
	}
	return false
}

func validSkillNameValue(name string) bool {
	return len(name) <= 64 && validSkillName.MatchString(name)
}

func atomicWrite(destination string, contents []byte) error {
	return atomicWriteWithOperations(destination, contents,
		func(file *os.File) error { return file.Sync() },
		atomicReplace,
		securefile.SyncParentDirectory,
	)
}

func atomicWriteWithOperations(
	destination string,
	contents []byte,
	syncFile func(*os.File) error,
	replace func(string, string) error,
	syncParent func(string) error,
) (returnedErr error) {
	directory := filepath.Dir(destination)
	file, err := os.CreateTemp(directory, "."+filepath.Base(destination)+".tmp-*")
	if err != nil {
		return err
	}
	temporary := file.Name()
	defer func() {
		_ = file.Close()
		_ = os.Remove(temporary)
	}()
	if err := file.Chmod(0o644); err != nil {
		return err
	}
	if _, err := file.Write(contents); err != nil {
		return err
	}
	if err := syncFile(file); err != nil {
		return fmt.Errorf("sync generated skill: %w", err)
	}
	if err := file.Close(); err != nil {
		return err
	}
	if err := replace(temporary, destination); err != nil {
		return err
	}
	if err := syncParent(directory); err != nil {
		return &securefile.ReplacementError{Err: fmt.Errorf("sync generated skill directory: %w", err)}
	}
	return nil
}

func fatalf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
